-- Generated by `pnpm library:seed` from content/curriculum. Do not edit by hand.
-- Curriculum sample: 6 files, 15 strands, 265 attentes (70 overall, 195 contenus).
-- Paraphrased summaries, not the official text: every row is unverified (D-030) and shows
-- « À vérifier ». Attentes that supabase/seed.sql already has keep their id and wording;
-- only their sort order follows the files. Loaded before the demo library (20_…).
do $lynxseed$
declare
  v_count integer;
begin
  -- fra fra-2023: 4 strands (from fra-2023-3e.json)
  insert into public.strands (id, subject_id, code, label_fr, label_en, curriculum_version,
    sort_order)
  select v.id::uuid, s.id, v.code, v.label_fr, v.label_en, 'fra-2023', v.sort_order
  from (values
    ('e91c63be-103b-5862-851d-ac202d35f418', 'A', $lynxcurr$Liens et applications en littératie$lynxcurr$, null, 1),
    ('e13b6bab-ed59-5577-9980-1bc2abdb5d8f', 'B', $lynxcurr$Fondements de la langue$lynxcurr$, null, 2),
    ('c29b7f00-1b42-5304-8a77-da3a877f0d52', 'C', $lynxcurr$Compréhension : comprendre et réagir à des textes$lynxcurr$, null, 3),
    ('496685a0-58f9-59d2-a015-9a215125aff0', 'D', $lynxcurr$Composition : exprimer ses idées et créer des textes$lynxcurr$, null, 4)
  ) as v (id, code, label_fr, label_en, sort_order)
  join public.subjects s on s.code = 'fra' and s.board_id is null
  on conflict (subject_id, curriculum_version, code) do update
    set sort_order = excluded.sort_order;
  get diagnostics v_count = row_count;
  if v_count <> 4 then
    raise exception 'curriculum seed: % of % strands of % written (is the standard subject missing?)',
      v_count, 4, 'fra fra-2023';
  end if;

  -- mat mat-2020: 6 strands (from mat-2020-3e.json)
  insert into public.strands (id, subject_id, code, label_fr, label_en, curriculum_version,
    sort_order)
  select v.id::uuid, s.id, v.code, v.label_fr, v.label_en, 'mat-2020', v.sort_order
  from (values
    ('83ab430d-25f5-5010-b5bd-ee6466799f99', 'A', $lynxcurr$Apprentissage socioémotionnel en mathématiques et processus mathématiques$lynxcurr$, null, 1),
    ('68545dbc-2474-569f-8dd1-9a8d15c3380a', 'B', $lynxcurr$Nombres$lynxcurr$, null, 2),
    ('e7256bae-19d5-5840-b8e8-bc4e2be98a96', 'C', $lynxcurr$Algèbre$lynxcurr$, null, 3),
    ('a922b4d6-bbf2-5daf-a621-c610bcd3d4d3', 'D', $lynxcurr$Données$lynxcurr$, null, 4),
    ('6c8156b3-d2a0-5baa-aa23-f48aed4444cd', 'E', $lynxcurr$Sens de l’espace$lynxcurr$, null, 5),
    ('2079f7ce-a527-520f-bb5d-e9fd77c60f1a', 'F', $lynxcurr$Littératie financière$lynxcurr$, null, 6)
  ) as v (id, code, label_fr, label_en, sort_order)
  join public.subjects s on s.code = 'mat' and s.board_id is null
  on conflict (subject_id, curriculum_version, code) do update
    set sort_order = excluded.sort_order;
  get diagnostics v_count = row_count;
  if v_count <> 6 then
    raise exception 'curriculum seed: % of % strands of % written (is the standard subject missing?)',
      v_count, 6, 'mat mat-2020';
  end if;

  -- sci sci-2022: 5 strands (from sci-2022-3e.json)
  insert into public.strands (id, subject_id, code, label_fr, label_en, curriculum_version,
    sort_order)
  select v.id::uuid, s.id, v.code, v.label_fr, v.label_en, 'sci-2022', v.sort_order
  from (values
    ('699244d6-e6e6-5fcf-9f56-273a56a2b445', 'A', $lynxcurr$Habiletés en STIM et liens$lynxcurr$, null, 1),
    ('f285eb6d-230c-515d-841a-cba8f449bf2b', 'B', $lynxcurr$Systèmes vivants$lynxcurr$, null, 2),
    ('8d34bdb0-21b5-5e36-9825-ac622785b1f5', 'C', $lynxcurr$Matière et énergie$lynxcurr$, null, 3),
    ('c6f4e794-90bb-5b31-bd55-cfb76a4e864e', 'D', $lynxcurr$Structures et mécanismes$lynxcurr$, null, 4),
    ('014700a4-4837-54c5-8b19-20111b75b4b9', 'E', $lynxcurr$Systèmes de la Terre et de l’espace$lynxcurr$, null, 5)
  ) as v (id, code, label_fr, label_en, sort_order)
  join public.subjects s on s.code = 'sci' and s.board_id is null
  on conflict (subject_id, curriculum_version, code) do update
    set sort_order = excluded.sort_order;
  get diagnostics v_count = row_count;
  if v_count <> 5 then
    raise exception 'curriculum seed: % of % strands of % written (is the standard subject missing?)',
      v_count, 5, 'sci sci-2022';
  end if;

  -- fra-2023-3e.json: 12 overall attentes
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, null::uuid,
    'overall'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'fra-2023', false, $lynxcurr$Résumé paraphrasé du curriculum de français de l’Ontario (2023), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('f06b83d3-ae6e-57d0-8b27-e235d5f6d7ac', '3', 'A', 'A1', $lynxcurr$Reconnaître et utiliser les compétences transférables (pensée critique, communication, collaboration, créativité, apprentissage autonome, citoyenneté) dans ses apprentissages en littératie.$lynxcurr$, null, 1),
    ('e340cd9e-35f6-5962-95f3-35796610bf70', '3', 'A', 'A2', $lynxcurr$Démontrer une compréhension de la littératie médiatique numérique et utiliser les médias numériques de façon sécuritaire, responsable et éthique.$lynxcurr$, null, 3),
    ('e3c3c380-be4a-5c95-8e26-6c0989800888', '3', 'A', 'A3', $lynxcurr$Appliquer ses compétences en littératie dans d’autres matières et reconnaître l’apport de diverses communautés, dont les communautés francophones et les Premières Nations, les Métis et les Inuit.$lynxcurr$, null, 6),
    ('0f7c1d9d-5fba-5383-b9cb-6d5335df1efc', '3', 'B', 'B1', $lynxcurr$Utiliser des habiletés d’écoute, d’expression orale et de communication non verbale pour interagir dans diverses situations.$lynxcurr$, null, 9),
    ('b0790485-c9bd-5fed-8154-492e278bcf25', '3', 'B', 'B2', $lynxcurr$Utiliser ses connaissances des sons, des lettres, des mots et de leur sens pour lire et écrire avec de plus en plus d’aisance.$lynxcurr$, null, 12),
    ('8f8900ff-dc19-5705-b9c9-176cd46de368', '3', 'B', 'B3', $lynxcurr$Appliquer ses connaissances des conventions linguistiques (syntaxe, grammaire, ponctuation) pour lire et écrire.$lynxcurr$, null, 16),
    ('0c6ff4fc-cfbc-57c5-9272-81b0de12c252', '3', 'C', 'C1', $lynxcurr$Utiliser des stratégies pour comprendre divers textes, dont des textes informatifs, et réagir à ce qu’elle ou il lit.$lynxcurr$, null, 20),
    ('33932ef3-ce68-51a6-90e8-8ac45ee06758', '3', 'C', 'C2', $lynxcurr$Appliquer des stratégies de compréhension (se poser des questions, faire des liens, faire des inférences, vérifier sa compréhension) pour construire le sens de textes variés.$lynxcurr$, null, 25),
    ('8790d47c-5710-5ec8-bfd2-66c1f731623c', '3', 'C', 'C3', $lynxcurr$Analyser des textes de façon critique en tenant compte du point de vue, de l’intention et des personnes représentées, et justifier sa réaction.$lynxcurr$, null, 30),
    ('7107f952-09b7-5df2-a1e6-5e705fa6160b', '3', 'D', 'D1', $lynxcurr$Planifier et rédiger de courts textes pour communiquer de l’information à un public donné.$lynxcurr$, null, 33),
    ('424016ed-e069-5186-bed2-bb072255d466', '3', 'D', 'D2', $lynxcurr$Rédiger des textes de divers genres en choisissant les mots, les phrases et la structure qui conviennent à l’intention et au public.$lynxcurr$, null, 37),
    ('cea535bf-88b0-5500-b4a9-d1ebcbf0d322', '3', 'D', 'D3', $lynxcurr$Corriger, publier et présenter ses textes, et réfléchir à ses stratégies d’écriture.$lynxcurr$, null, 41)
  ) as v (id, grade_code, strand_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'fra' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'fra-2023' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 12 then
    raise exception 'curriculum seed: %: % of % overall attentes written (a missing subject, grade, strand, or an attente the database has with another kind, strand or parent)',
      'fra-2023-3e.json', v_count, 12;
  end if;
  -- fra-2023-3e.json: 32 contenus (specific attentes)
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, p.id,
    'specific'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'fra-2023', false, $lynxcurr$Résumé paraphrasé du curriculum de français de l’Ontario (2023), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('db0ee26d-9e39-525f-be2f-721975282996', '3', 'A', 'A1', 'A1.1', $lynxcurr$Décrire comment les compétences transférables l’aident à lire, à écrire et à communiquer oralement, en classe et ailleurs.$lynxcurr$, null, 2),
    ('f90ec60a-0d44-5990-8314-f69eebffb69f', '3', 'A', 'A2', 'A2.1', $lynxcurr$Utiliser des outils numériques pour chercher de l’information, communiquer et créer des textes en français.$lynxcurr$, null, 4),
    ('d4384179-64c8-5c04-9449-8f018098e025', '3', 'A', 'A2', 'A2.2', $lynxcurr$Adopter des comportements sécuritaires et respectueux en ligne, par exemple protéger ses renseignements personnels et respecter le travail des autres.$lynxcurr$, null, 5),
    ('7d60c78b-1c09-518f-9fc5-2aa6c22cafa6', '3', 'A', 'A3', 'A3.1', $lynxcurr$Utiliser ses compétences en lecture, en écriture et en communication orale dans les autres matières.$lynxcurr$, null, 7),
    ('71417e5b-738d-51e6-b06d-67cebc4f324a', '3', 'A', 'A3', 'A3.2', $lynxcurr$Explorer des textes créés par des autrices et des auteurs de diverses communautés, dont des Franco-Ontariennes et des Franco-Ontariens, et des Premières Nations, des Métis et des Inuit.$lynxcurr$, null, 8),
    ('4a1c21da-c940-5a0d-aca8-a45cd1416c27', '3', 'B', 'B1', 'B1.1', $lynxcurr$Écouter activement pour comprendre un message oral et en dégager l’information importante.$lynxcurr$, null, 10),
    ('019e5141-cbc7-575a-945b-d0bb1946e3fb', '3', 'B', 'B1', 'B1.2', $lynxcurr$Participer à des échanges en respectant les tours de parole, en posant des questions et en tenant compte des idées des autres.$lynxcurr$, null, 11),
    ('1291f179-5a10-5570-a190-a7bde89f5fdf', '3', 'B', 'B2', 'B2.1', $lynxcurr$Lire et orthographier des mots à l’aide des correspondances entre les sons et les lettres et des mots d’usage fréquent.$lynxcurr$, null, 13),
    ('50fa8d8a-4b19-50af-a1b1-ffaf3782c8e6', '3', 'B', 'B2', 'B2.2', $lynxcurr$Enrichir son vocabulaire à l’aide du contexte, des familles de mots et d’outils de référence.$lynxcurr$, null, 14),
    ('b6f6ace2-7048-516d-a7ec-5f12df9ac18f', '3', 'B', 'B2', 'B2.3', $lynxcurr$Lire à voix haute avec fluidité, c’est-à-dire avec précision, à un rythme approprié et avec une intonation expressive.$lynxcurr$, null, 15),
    ('09098353-1965-52e3-a60c-8ec5b313b5c6', '3', 'B', 'B3', 'B3.1', $lynxcurr$Construire des phrases bien formées (sujet, verbe, complément) et les enrichir, par exemple à l’aide d’adjectifs et de compléments.$lynxcurr$, null, 17),
    ('cb53b262-3b88-57f3-94e2-deea9419b852', '3', 'B', 'B3', 'B3.2', $lynxcurr$Faire les accords dans le groupe du nom (déterminant, nom, adjectif) et accorder le verbe avec son sujet dans des phrases simples.$lynxcurr$, null, 18),
    ('e4fdd25f-e5ef-58fa-b185-a3532f0f67fc', '3', 'B', 'B3', 'B3.3', $lynxcurr$Utiliser correctement la majuscule et les signes de ponctuation courants (point, point d’interrogation, point d’exclamation, virgule dans une énumération).$lynxcurr$, null, 19),
    ('5f3e1c87-5df6-5e18-b61b-9226012a091a', '3', 'C', 'C1', 'C1.1', $lynxcurr$Faire des prédictions et activer ses connaissances antérieures avant la lecture.$lynxcurr$, null, 21),
    ('127cc4d0-6ab1-55c2-8c94-84d11a7cf1d8', '3', 'C', 'C1', 'C1.2', $lynxcurr$Repérer l’idée principale et quelques détails importants d’un texte informatif.$lynxcurr$, null, 22),
    ('87f458c9-ddcb-539a-9aeb-a3dcd18b2cc5', '3', 'C', 'C1', 'C1.3', $lynxcurr$Utiliser les caractéristiques d’un texte informatif (titres, images, légendes) pour trouver de l’information.$lynxcurr$, null, 23),
    ('bfba7bfa-99b5-521d-b36a-b59d40579c7b', '3', 'C', 'C1', 'C1.4', $lynxcurr$Reconnaître les caractéristiques de divers genres de textes (conte, récit, texte informatif, poème, bande dessinée) et leur intention.$lynxcurr$, null, 24),
    ('06fc9b51-b97e-5f76-9869-3d9f5a619870', '3', 'C', 'C2', 'C2.1', $lynxcurr$Se poser des questions avant, pendant et après la lecture pour approfondir sa compréhension.$lynxcurr$, null, 26),
    ('fdcc1bb7-ce52-5e9c-bd7e-48f2d2a5d1dd', '3', 'C', 'C2', 'C2.2', $lynxcurr$Faire des liens entre un texte et ses expériences personnelles, d’autres textes et le monde qui l’entoure.$lynxcurr$, null, 27),
    ('3369fc7b-18d7-5fb7-8d8c-65ae8ab5e33e', '3', 'C', 'C2', 'C2.3', $lynxcurr$Faire des inférences simples à partir d’indices du texte et des illustrations.$lynxcurr$, null, 28),
    ('b11836d3-9720-504f-9031-1ecb296610bb', '3', 'C', 'C2', 'C2.4', $lynxcurr$Vérifier sa compréhension et utiliser des stratégies de dépannage, comme relire, lire la suite ou observer les illustrations.$lynxcurr$, null, 29),
    ('65ab32f6-5733-5869-936e-820631d9a3ba', '3', 'C', 'C3', 'C3.1', $lynxcurr$Reconnaître le point de vue présenté dans un texte et se demander quelles voix sont absentes.$lynxcurr$, null, 31),
    ('897ca224-a6ae-5532-91bd-a0aa88cdd818', '3', 'C', 'C3', 'C3.2', $lynxcurr$Exprimer une réaction personnelle à un texte et la justifier à l’aide d’exemples tirés du texte.$lynxcurr$, null, 32),
    ('935153f1-b489-513f-9fd2-996f8b5921aa', '3', 'D', 'D1', 'D1.1', $lynxcurr$Organiser ses idées à l’aide d’un organisateur graphique avant d’écrire.$lynxcurr$, null, 34),
    ('5d88ac33-2850-5324-beba-bd1b9c3a7596', '3', 'D', 'D1', 'D1.2', $lynxcurr$Trouver et développer des idées pour écrire à partir de ses expériences, de ses lectures et de discussions.$lynxcurr$, null, 35),
    ('0ceb65fa-11d0-5a3e-8eef-a5da23e13003', '3', 'D', 'D1', 'D1.3', $lynxcurr$Recueillir de l’information dans quelques sources, imprimées ou numériques, pour appuyer ses idées.$lynxcurr$, null, 36),
    ('9af28bd6-1289-5066-94ed-e214bc5ccf55', '3', 'D', 'D2', 'D2.1', $lynxcurr$Écrire des textes de divers genres (récit, texte informatif, texte d’opinion, poème) en respectant leurs caractéristiques.$lynxcurr$, null, 38),
    ('c6e9211e-1eec-5725-8861-a357efd92228', '3', 'D', 'D2', 'D2.3', $lynxcurr$Choisir des mots précis et variés (verbes d’action, adjectifs, synonymes) pour rendre son texte clair et intéressant.$lynxcurr$, null, 39),
    ('505bf434-c295-5b3f-a632-026bc0bed6e2', '3', 'D', 'D2', 'D2.6', $lynxcurr$Réviser son brouillon pour améliorer la clarté et l’enchaînement des idées, de façon autonome ou avec l’aide de ses pairs.$lynxcurr$, null, 40),
    ('0ac278d5-11ac-5dc5-8926-08a5c12c11cd', '3', 'D', 'D3', 'D3.1', $lynxcurr$Corriger son texte à l’aide d’outils (liste de vérification, dictionnaire, banque de mots) pour produire une version finale.$lynxcurr$, null, 42),
    ('d1dd7878-8ee2-5419-bcf6-011dc61e8151', '3', 'D', 'D3', 'D3.2', $lynxcurr$Publier ou présenter ses textes dans des formats variés, imprimés, oraux ou numériques.$lynxcurr$, null, 43),
    ('bed9c8cd-83b3-56db-97a4-7b98c6c1228e', '3', 'D', 'D3', 'D3.3', $lynxcurr$Réfléchir à ses forces et à ses défis en écriture et se fixer un objectif d’amélioration.$lynxcurr$, null, 44)
  ) as v (id, grade_code, strand_code, parent_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'fra' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  join public.curriculum_expectations p on p.subject_id = s.id and p.grade_code = g.code
    and p.curriculum_version = 'fra-2023' and p.code = v.parent_code and p.kind = 'overall'
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'fra-2023' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 32 then
    raise exception 'curriculum seed: %: % of % contenus (specific attentes) written (a missing subject, grade, strand or overall attente, or an attente the database has with another kind, strand or parent)',
      'fra-2023-3e.json', v_count, 32;
  end if;

  -- fra-2023-5e.json: 12 overall attentes
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, null::uuid,
    'overall'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'fra-2023', false, $lynxcurr$Résumé paraphrasé du curriculum de français de l’Ontario (2023), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('95700e54-9d2c-548d-af87-a8ecba75b6d3', '5', 'A', 'A1', $lynxcurr$Reconnaître et utiliser les compétences transférables (pensée critique, communication, collaboration, créativité, apprentissage autonome, citoyenneté) dans ses apprentissages en littératie.$lynxcurr$, null, 1),
    ('b11e0191-dfba-5607-8a1a-1ce2f69e8380', '5', 'A', 'A2', $lynxcurr$Démontrer une compréhension de la littératie médiatique numérique et utiliser les médias numériques de façon sécuritaire, responsable et éthique.$lynxcurr$, null, 3),
    ('5f04dedc-4491-54e8-a9b6-f3970d5b603d', '5', 'A', 'A3', $lynxcurr$Appliquer ses compétences en littératie dans d’autres matières et reconnaître l’apport de diverses communautés, dont les communautés francophones et les Premières Nations, les Métis et les Inuit.$lynxcurr$, null, 6),
    ('4a4bb265-c7b5-5bc3-8f66-e82bfd097755', '5', 'B', 'B1', $lynxcurr$Utiliser des habiletés d’écoute, d’expression orale et de communication non verbale pour interagir dans diverses situations.$lynxcurr$, null, 9),
    ('9d699d16-0559-559d-9693-4af2027db031', '5', 'B', 'B2', $lynxcurr$Utiliser ses connaissances des mots, de leur formation et de leur sens pour lire et écrire avec aisance.$lynxcurr$, null, 12),
    ('77d33f25-708c-5ed9-b722-8909eea9b470', '5', 'B', 'B3', $lynxcurr$Appliquer ses connaissances des conventions linguistiques (syntaxe, grammaire, ponctuation) pour lire et écrire.$lynxcurr$, null, 16),
    ('72f1ddee-3ef4-59f3-b801-353778bed069', '5', 'C', 'C1', $lynxcurr$Utiliser des stratégies pour comprendre divers textes, dont des textes informatifs et narratifs, et réagir à ce qu’elle ou il lit.$lynxcurr$, null, 20),
    ('24da5ada-e291-5512-80ed-ace8d3b2e2cb', '5', 'C', 'C2', $lynxcurr$Appliquer des stratégies de compréhension (se poser des questions, faire des liens, faire des inférences, vérifier sa compréhension) pour construire le sens de textes variés.$lynxcurr$, null, 25),
    ('5f81021e-05e1-550b-8dfd-e4c300f09ec0', '5', 'C', 'C3', $lynxcurr$Analyser des textes de façon critique en tenant compte du point de vue, de l’intention, des stéréotypes et des personnes représentées, et justifier sa réaction.$lynxcurr$, null, 30),
    ('7e6d8237-6e0c-58c1-96fa-ac5dcab9f102', '5', 'D', 'D1', $lynxcurr$Planifier et rédiger des textes variés pour communiquer de l’information et des idées à un public donné.$lynxcurr$, null, 33),
    ('00d8a652-735b-5f6e-b397-8bf73854ecb8', '5', 'D', 'D2', $lynxcurr$Rédiger des textes de divers genres en choisissant les mots, les phrases et la structure qui conviennent à l’intention et au public.$lynxcurr$, null, 37),
    ('e99332b1-229f-526d-a6d5-1020136ccbf8', '5', 'D', 'D3', $lynxcurr$Corriger, publier et présenter ses textes, et réfléchir à ses stratégies d’écriture.$lynxcurr$, null, 41)
  ) as v (id, grade_code, strand_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'fra' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'fra-2023' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 12 then
    raise exception 'curriculum seed: %: % of % overall attentes written (a missing subject, grade, strand, or an attente the database has with another kind, strand or parent)',
      'fra-2023-5e.json', v_count, 12;
  end if;
  -- fra-2023-5e.json: 32 contenus (specific attentes)
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, p.id,
    'specific'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'fra-2023', false, $lynxcurr$Résumé paraphrasé du curriculum de français de l’Ontario (2023), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('e3ce7904-5d22-5ace-be3a-b104b0cf3265', '5', 'A', 'A1', 'A1.1', $lynxcurr$Expliquer comment les compétences transférables l’aident à apprendre en littératie et dans d’autres contextes, et se fixer des objectifs pour les développer.$lynxcurr$, null, 2),
    ('d9175f33-579e-5126-8e40-739eb03147d3', '5', 'A', 'A2', 'A2.1', $lynxcurr$Utiliser des outils numériques pour chercher, évaluer et organiser de l’information, et pour créer des textes en français.$lynxcurr$, null, 4),
    ('4473b93d-1218-5952-ac50-81fa66fd4983', '5', 'A', 'A2', 'A2.2', $lynxcurr$Adopter des comportements sécuritaires, respectueux et éthiques en ligne, dont citer ses sources et protéger ses renseignements personnels.$lynxcurr$, null, 5),
    ('126d44b4-47b2-571e-bbd4-b78e41448daa', '5', 'A', 'A3', 'A3.1', $lynxcurr$Utiliser ses compétences en lecture, en écriture et en communication orale dans les autres matières, par exemple pour rédiger un compte rendu en sciences.$lynxcurr$, null, 7),
    ('4ef7c75b-a905-569c-aacf-46c6392a10e0', '5', 'A', 'A3', 'A3.2', $lynxcurr$Explorer et comparer des textes créés par des autrices et des auteurs de diverses communautés, dont des Franco-Ontariennes et des Franco-Ontariens, et des Premières Nations, des Métis et des Inuit.$lynxcurr$, null, 8),
    ('ba236931-3c35-58d8-9f65-63f31e4c53a3', '5', 'B', 'B1', 'B1.1', $lynxcurr$Écouter activement pour comprendre un message oral, en dégager l’information importante et distinguer les faits des opinions.$lynxcurr$, null, 10),
    ('65828c83-597c-50bb-908f-ec9f986a2c56', '5', 'B', 'B1', 'B1.2', $lynxcurr$Participer à des discussions en respectant les tours de parole, en reformulant les idées des autres et en justifiant son point de vue.$lynxcurr$, null, 11),
    ('78803090-99c3-529b-9d93-5cf56f4eb1e6', '5', 'B', 'B2', 'B2.1', $lynxcurr$Lire et orthographier des mots de plus en plus complexes, dont des mots d’usage fréquent et des termes propres aux matières étudiées.$lynxcurr$, null, 13),
    ('799dd62f-02db-5572-a207-d4da8323d274', '5', 'B', 'B2', 'B2.2', $lynxcurr$Enrichir son vocabulaire à l’aide du contexte, des préfixes, des suffixes, des familles de mots et du dictionnaire.$lynxcurr$, null, 14),
    ('75ee8958-009b-5cfc-b8d8-955e8a68259e', '5', 'B', 'B2', 'B2.3', $lynxcurr$Lire avec fluidité, c’est-à-dire avec précision, à un rythme approprié et avec une intonation adaptée au texte.$lynxcurr$, null, 15),
    ('65011ab5-a468-5dcf-99e0-fa964cc30f65', '5', 'B', 'B3', 'B3.1', $lynxcurr$Construire des phrases variées (déclaratives, interrogatives, exclamatives, impératives) et les enrichir à l’aide de compléments.$lynxcurr$, null, 17),
    ('db6ff21a-442c-57df-b925-e96ffcac893e', '5', 'B', 'B3', 'B3.2', $lynxcurr$Faire les accords dans le groupe du nom et accorder le verbe avec son sujet, y compris lorsque le sujet est éloigné du verbe.$lynxcurr$, null, 18),
    ('724048c2-89f0-56b1-b953-6ed1643086cc', '5', 'B', 'B3', 'B3.3', $lynxcurr$Utiliser correctement les signes de ponctuation, dont la virgule et les signes du dialogue (deux-points, tiret, guillemets).$lynxcurr$, null, 19),
    ('bb159bae-894d-51f3-b00f-42331e502c57', '5', 'C', 'C1', 'C1.1', $lynxcurr$Faire des prédictions et activer ses connaissances antérieures avant et pendant la lecture, puis vérifier ses prédictions.$lynxcurr$, null, 21),
    ('ee3c7d77-67ae-5b88-aa83-c00c4eaa82d1', '5', 'C', 'C1', 'C1.2', $lynxcurr$Dégager l’idée principale et les détails importants d’un texte informatif ou narratif.$lynxcurr$, null, 22),
    ('de1ffbc5-dcc4-531b-b392-9a1fe2177a71', '5', 'C', 'C1', 'C1.3', $lynxcurr$Utiliser les caractéristiques des textes informatifs (intertitres, encadrés, schémas, tableaux, glossaire) pour trouver et relier de l’information.$lynxcurr$, null, 23),
    ('d70c5a8d-9a40-5e8c-8c2f-156f829a8271', '5', 'C', 'C1', 'C1.4', $lynxcurr$Reconnaître les caractéristiques de divers genres de textes (récit d’aventures, légende, texte explicatif, texte d’opinion, poème) et leur intention.$lynxcurr$, null, 24),
    ('c279b1c9-0c1f-5395-9de1-8f63d1003d37', '5', 'C', 'C2', 'C2.1', $lynxcurr$Se poser des questions de différents types avant, pendant et après la lecture pour approfondir sa compréhension.$lynxcurr$, null, 26),
    ('63f6cf59-66da-506a-bf5f-840ca827702f', '5', 'C', 'C2', 'C2.2', $lynxcurr$Faire des liens entre des textes, ses expériences et des enjeux de sa communauté ou du monde.$lynxcurr$, null, 27),
    ('73a8d992-9e75-59a8-8518-65943b5ba1c9', '5', 'C', 'C2', 'C2.3', $lynxcurr$Faire des inférences à partir d’indices du texte pour dégager des sentiments, des motivations ou des liens de cause à effet.$lynxcurr$, null, 28),
    ('af3d75a3-ea9f-56c5-b43f-93098be0ca02', '5', 'C', 'C2', 'C2.4', $lynxcurr$Vérifier sa compréhension et choisir des stratégies de dépannage appropriées, comme relire, reformuler ou consulter un glossaire.$lynxcurr$, null, 29),
    ('8f7dcfda-a3b8-5ec8-a3b0-ee35fadd65f2', '5', 'C', 'C3', 'C3.1', $lynxcurr$Reconnaître le point de vue présenté dans un texte, repérer des stéréotypes ou des préjugés et se demander quelles voix sont absentes.$lynxcurr$, null, 31),
    ('1f0218e1-0c60-5feb-a0e1-288e1670a90d', '5', 'C', 'C3', 'C3.2', $lynxcurr$Exprimer une réaction à un texte et l’appuyer à l’aide d’exemples précis tirés du texte et de ses connaissances.$lynxcurr$, null, 32),
    ('149c8e61-b387-50df-bea0-89c4164e97ea', '5', 'D', 'D1', 'D1.1', $lynxcurr$Organiser ses idées et l’information recueillie à l’aide d’un organisateur graphique avant d’écrire.$lynxcurr$, null, 34),
    ('35d43bf7-ee21-5581-8d90-2684e4604b4f', '5', 'D', 'D1', 'D1.2', $lynxcurr$Trouver et développer des idées pour écrire en tenant compte de l’intention et du public.$lynxcurr$, null, 35),
    ('27b55526-9bcf-524d-b148-145b88b045d0', '5', 'D', 'D1', 'D1.3', $lynxcurr$Recueillir de l’information dans diverses sources, imprimées ou numériques, en vérifiant leur fiabilité et en notant les sources.$lynxcurr$, null, 36),
    ('4216660b-1d92-516e-bd30-e3197a740141', '5', 'D', 'D2', 'D2.1', $lynxcurr$Écrire des textes de divers genres (récit, texte explicatif, texte d’opinion, compte rendu, poème) en respectant leurs caractéristiques.$lynxcurr$, null, 38),
    ('50f95e23-6a3e-5303-b52b-7e4340af7154', '5', 'D', 'D2', 'D2.3', $lynxcurr$Choisir un vocabulaire précis et varié, dont des termes propres aux matières et des marqueurs de relation, pour rendre son texte clair et cohérent.$lynxcurr$, null, 39),
    ('1edf8fbc-3ecc-52cd-bb0d-54b169c93a56', '5', 'D', 'D2', 'D2.6', $lynxcurr$Réviser son brouillon pour améliorer la clarté, la cohérence et l’enchaînement des idées, de façon autonome ou avec ses pairs.$lynxcurr$, null, 40),
    ('764de429-2b23-56a9-a410-61e730190270', '5', 'D', 'D3', 'D3.1', $lynxcurr$Corriger son texte à l’aide d’outils (grille de vérification, dictionnaire, correcticiel) pour produire une version finale soignée.$lynxcurr$, null, 42),
    ('a5f8ed22-aee4-5c82-989f-17ddc6d2885c', '5', 'D', 'D3', 'D3.2', $lynxcurr$Publier ou présenter ses textes dans des formats variés, imprimés, oraux ou numériques, en tenant compte du public.$lynxcurr$, null, 43),
    ('4cb7d920-8cc5-5f5d-8704-4712e84ef88d', '5', 'D', 'D3', 'D3.3', $lynxcurr$Réfléchir aux stratégies d’écriture qui l’aident le plus et se fixer des objectifs d’amélioration.$lynxcurr$, null, 44)
  ) as v (id, grade_code, strand_code, parent_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'fra' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  join public.curriculum_expectations p on p.subject_id = s.id and p.grade_code = g.code
    and p.curriculum_version = 'fra-2023' and p.code = v.parent_code and p.kind = 'overall'
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'fra-2023' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 32 then
    raise exception 'curriculum seed: %: % of % contenus (specific attentes) written (a missing subject, grade, strand or overall attente, or an attente the database has with another kind, strand or parent)',
      'fra-2023-5e.json', v_count, 32;
  end if;

  -- mat-2020-3e.json: 12 overall attentes
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, null::uuid,
    'overall'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'mat-2020', false, $lynxcurr$Résumé paraphrasé du curriculum de mathématiques de l’Ontario (2020), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('e20665e1-aab9-5afb-a740-7a4d9bcbbeb1', '3', 'A', 'A1', $lynxcurr$Mettre en pratique des habiletés socioémotionnelles (reconnaître et gérer ses émotions, persévérer, collaborer, avoir confiance en soi, penser de façon critique et créative) en utilisant les processus mathématiques dans tous les domaines.$lynxcurr$, null, 1),
    ('d4cde2b8-2aca-547a-b91d-e782e4cd3ec4', '3', 'B', 'B1', $lynxcurr$Démontrer une compréhension des nombres naturels jusqu’à 1 000 et de leurs relations.$lynxcurr$, null, 2),
    ('84fce340-41cb-5242-8e36-100b860129e9', '3', 'B', 'B2', $lynxcurr$Utiliser ses connaissances des nombres et des opérations pour résoudre des problèmes.$lynxcurr$, null, 9),
    ('19968d6e-fe55-57c2-b30d-cb3d996a03dc', '3', 'C', 'C1', $lynxcurr$Reconnaître, décrire, prolonger et créer diverses suites, dont des suites tirées de la vie courante, et faire des prédictions à leur sujet.$lynxcurr$, null, 17),
    ('acf4b9a6-f046-5b0c-8ded-1ee64173d3b3', '3', 'C', 'C2', $lynxcurr$Démontrer une compréhension des variables, des expressions, des égalités et des inégalités, et appliquer cette compréhension dans divers contextes.$lynxcurr$, null, 22),
    ('d1f82d6b-0a6c-5db9-ad47-c198af31b881', '3', 'C', 'C3', $lynxcurr$Résoudre des problèmes et créer des représentations informatiques de situations mathématiques à l’aide de concepts et d’habiletés de codage.$lynxcurr$, null, 26),
    ('0c3b9788-804b-5e2f-b5f9-3f97bb5701bf', '3', 'C', 'C4', $lynxcurr$Appliquer le processus de modélisation mathématique pour représenter et analyser des situations de la vie courante, faire des prédictions et mieux les comprendre.$lynxcurr$, null, 29),
    ('11e6a6dc-0117-5faa-bc3a-db4f1ece7297', '3', 'D', 'D1', $lynxcurr$Gérer, analyser et utiliser des données pour formuler des arguments convaincants et prendre des décisions éclairées dans des contextes de la vie courante.$lynxcurr$, null, 30),
    ('248fc841-f691-570d-9298-d217b153483c', '3', 'D', 'D2', $lynxcurr$Décrire la probabilité que des événements se produisent et utiliser cette information pour faire des prédictions.$lynxcurr$, null, 36),
    ('32f8e0fb-e90d-59a9-a939-9e6c1be43488', '3', 'E', 'E1', $lynxcurr$Décrire et représenter des formes, des positions et des déplacements en appliquant des propriétés géométriques et des relations spatiales pour s’orienter dans le monde qui nous entoure.$lynxcurr$, null, 38),
    ('7f1e0d38-5fb8-503a-94fe-56089e342d5a', '3', 'E', 'E2', $lynxcurr$Comparer, estimer et déterminer des mesures dans divers contextes.$lynxcurr$, null, 41),
    ('69c490c0-d658-5e2b-85de-3e3dfa7eddce', '3', 'F', 'F1', $lynxcurr$Démontrer une compréhension de la valeur et de l’utilisation de la monnaie canadienne.$lynxcurr$, null, 45)
  ) as v (id, grade_code, strand_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'mat' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'mat-2020' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 12 then
    raise exception 'curriculum seed: %: % of % overall attentes written (a missing subject, grade, strand, or an attente the database has with another kind, strand or parent)',
      'mat-2020-3e.json', v_count, 12;
  end if;
  -- mat-2020-3e.json: 34 contenus (specific attentes)
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, p.id,
    'specific'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'mat-2020', false, $lynxcurr$Résumé paraphrasé du curriculum de mathématiques de l’Ontario (2020), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('c4c49398-d5b6-5253-8823-2081e7a3d41f', '3', 'B', 'B1', 'B1.1', $lynxcurr$Lire, représenter, composer et décomposer des nombres naturels jusqu’à 1 000 de différentes façons.$lynxcurr$, null, 3),
    ('a9257782-8b96-530e-abb5-4e400ce6b9e7', '3', 'B', 'B1', 'B1.2', $lynxcurr$Comparer et ordonner des nombres naturels jusqu’à 1 000.$lynxcurr$, null, 4),
    ('6ab6c2eb-d8d2-5edf-b0c4-5c1f53055791', '3', 'B', 'B1', 'B1.3', $lynxcurr$Arrondir des nombres naturels à la dizaine ou à la centaine près dans divers contextes.$lynxcurr$, null, 5),
    ('14aa0034-7cda-538c-81ba-7687c00bb7ea', '3', 'B', 'B1', 'B1.4', $lynxcurr$Compter jusqu’à 1 000, notamment par bonds de 50, de 100 et de 200, à l’aide de divers outils et stratégies.$lynxcurr$, null, 6),
    ('2efe917f-7d18-5d2c-a4a7-e4d1b86370dc', '3', 'B', 'B1', 'B1.6', $lynxcurr$Représenter, résoudre et comparer à l’aide de dessins des problèmes de partage équitable d’au plus 20 objets entre 2, 3, 4, 5, 6, 8 ou 10 personnes, dont le résultat peut être un nombre naturel, un nombre fractionnaire ou une fraction.$lynxcurr$, null, 7),
    ('e2adfe93-f23f-54aa-9c8d-889816149b0c', '3', 'B', 'B1', 'B1.7', $lynxcurr$Résoudre des problèmes de partage équitable en trouvant et en utilisant des fractions équivalentes, par exemple des demis, des quarts et des huitièmes, des tiers et des sixièmes, ou des cinquièmes et des dixièmes.$lynxcurr$, null, 8),
    ('f580cb5b-9ca5-5b5f-b455-62e64f3ca605', '3', 'B', 'B2', 'B2.1', $lynxcurr$Utiliser les propriétés des opérations et les liens entre la multiplication et la division pour résoudre des problèmes et vérifier ses calculs.$lynxcurr$, null, 10),
    ('d1a6dc08-e6de-5e5e-8f8d-58d0640c515d', '3', 'B', 'B2', 'B2.2', $lynxcurr$Se rappeler les faits de multiplication par 2, 5 et 10 et les faits de division qui s’y rattachent.$lynxcurr$, null, 11),
    ('bda2ac2c-8e8d-5235-aecd-fc09f7e467c2', '3', 'B', 'B2', 'B2.3', $lynxcurr$Utiliser des stratégies de calcul mental, dont l’estimation, pour additionner et soustraire des nombres naturels dont la somme ne dépasse pas 1 000, et expliquer les stratégies utilisées.$lynxcurr$, null, 12),
    ('c4cd59f4-8bed-52e4-970c-07d220a05c7f', '3', 'B', 'B2', 'B2.4', $lynxcurr$Expliquer le fonctionnement d’algorithmes d’addition et de soustraction en les reliant à d’autres outils et stratégies de calcul.$lynxcurr$, null, 13),
    ('15a474e7-df7e-5b29-9976-e19a7bae4be0', '3', 'B', 'B2', 'B2.5', $lynxcurr$Représenter et résoudre des problèmes d’addition et de soustraction de nombres naturels dont la somme ne dépasse pas 1 000, à l’aide de divers outils et algorithmes.$lynxcurr$, null, 14),
    ('4abdf24a-f1b6-58e6-9293-aa3664daa3ac', '3', 'B', 'B2', 'B2.6', $lynxcurr$Représenter la multiplication jusqu’à 10 × 10 et la division jusqu’à 100 ÷ 10 à l’aide d’outils et de dessins, dont des dispositions rectangulaires.$lynxcurr$, null, 15),
    ('0de7b927-63e0-5d50-8b03-7671982766ca', '3', 'B', 'B2', 'B2.7', $lynxcurr$Représenter et résoudre des problèmes de multiplication et de division, y compris des problèmes où l’on forme des groupes de demis, de tiers ou de quarts.$lynxcurr$, null, 16),
    ('cf70d6a3-125e-5f2f-9b1c-c1ff74129948', '3', 'C', 'C1', 'C1.1', $lynxcurr$Reconnaître et décrire des suites à motif répété, des suites croissantes et des suites décroissantes, y compris dans la vie courante.$lynxcurr$, null, 18),
    ('0827fac6-2250-56aa-8463-92511a1b829e', '3', 'C', 'C1', 'C1.2', $lynxcurr$Créer des suites et les traduire d’une représentation à une autre, dont des tables de valeurs.$lynxcurr$, null, 19),
    ('d7d26731-5410-526c-a188-557fd1becb25', '3', 'C', 'C1', 'C1.3', $lynxcurr$Déterminer la règle d’une suite pour la prolonger, trouver des éléments manquants et justifier des prédictions.$lynxcurr$, null, 20),
    ('abe39b89-6fbd-5d05-9bf3-2304c5dfd73a', '3', 'C', 'C1', 'C1.4', $lynxcurr$Créer et décrire des suites qui illustrent des relations entre des nombres naturels jusqu’à 1 000.$lynxcurr$, null, 21),
    ('5193045a-4203-5778-a7d8-d01f0a9b5e5c', '3', 'C', 'C2', 'C2.1', $lynxcurr$Décrire comment on utilise des variables et s’en servir dans divers contextes.$lynxcurr$, null, 23),
    ('2ea18477-9fb0-5814-8770-fd314b07833e', '3', 'C', 'C2', 'C2.2', $lynxcurr$Déterminer si des expressions d’addition, de soustraction, de multiplication et de division sont équivalentes ou non.$lynxcurr$, null, 24),
    ('d4fe3334-2534-53a9-a158-fef5bd4c7a08', '3', 'C', 'C2', 'C2.3', $lynxcurr$Reconnaître et utiliser des relations d’égalité entre des nombres naturels jusqu’à 1 000 dans divers contextes.$lynxcurr$, null, 25),
    ('9c91d4f3-96b3-54ed-a71a-2756c7b9d0c1', '3', 'C', 'C3', 'C3.1', $lynxcurr$Écrire et exécuter du code comprenant des événements séquentiels, simultanés et répétitifs pour résoudre des problèmes.$lynxcurr$, null, 27),
    ('49821f68-6133-55f3-a1bf-bda0b833dd8e', '3', 'C', 'C3', 'C3.2', $lynxcurr$Lire et modifier du code existant comprenant des événements séquentiels, simultanés et répétitifs, et décrire l’effet des changements sur le résultat.$lynxcurr$, null, 28),
    ('98e1cb6b-5da4-5ad0-856f-bd5e912b0a73', '3', 'D', 'D1', 'D1.1', $lynxcurr$Trier des ensembles de données selon deux ou trois attributs à l’aide de tableaux et de diagrammes (diagramme de Venn, diagramme de Carroll, diagramme en arbre).$lynxcurr$, null, 31),
    ('cc15b714-9b7a-5de8-8b12-5186454abbe0', '3', 'D', 'D1', 'D1.2', $lynxcurr$Recueillir des données qualitatives et quantitatives par des observations, des expériences ou des entrevues pour répondre à des questions d’intérêt, et les organiser dans des tableaux des effectifs.$lynxcurr$, null, 32),
    ('50a83a17-3215-5fa4-bac3-f5c5464e66f7', '3', 'D', 'D1', 'D1.3', $lynxcurr$Présenter des données dans des pictogrammes (un symbole pouvant représenter plusieurs données) et des diagrammes à bandes, avec une source, un titre, des étiquettes et une échelle appropriée.$lynxcurr$, null, 33),
    ('564a0566-dc80-57ee-884f-b8b74041ad59', '3', 'D', 'D1', 'D1.4', $lynxcurr$Déterminer le mode d’un ensemble de données, s’il y en a un, et expliquer ce qu’il indique au sujet des données.$lynxcurr$, null, 34),
    ('fd2e4753-4285-54bc-93b9-66076eff7efe', '3', 'D', 'D1', 'D1.5', $lynxcurr$Analyser des données présentées de diverses façons en posant des questions et en y répondant, tirer des conclusions, puis formuler des arguments convaincants et prendre des décisions éclairées.$lynxcurr$, null, 35),
    ('06356aff-47bd-5ee8-8eda-833899871581', '3', 'D', 'D2', 'D2.1', $lynxcurr$Utiliser un vocabulaire mathématique, dont les termes « impossible », « possible » et « certain », pour décrire la probabilité que des événements se produisent et faire des prédictions.$lynxcurr$, null, 37),
    ('22bd41e9-8306-55cd-b27c-cd165947df35', '3', 'E', 'E1', 'E1.1', $lynxcurr$Trier et reconnaître des figures planes en comparant le nombre de côtés, la longueur des côtés, les angles et le nombre d’axes de symétrie.$lynxcurr$, null, 39),
    ('c50e007a-9e08-530b-b81d-307b1e1e892a', '3', 'E', 'E1', 'E1.2', $lynxcurr$Composer et décomposer diverses structures, et nommer les figures planes et les solides qui les composent.$lynxcurr$, null, 40),
    ('011c99d0-d981-56e5-9f0e-3d18e84bf995', '3', 'E', 'E2', 'E2.1', $lynxcurr$Estimer, mesurer et comparer le périmètre de polygones et de figures à côtés courbes à l’aide d’unités de longueur appropriées, et construire des polygones d’un périmètre donné.$lynxcurr$, null, 42),
    ('79f9c117-6cc2-56fd-99f8-d16ab59c85fc', '3', 'E', 'E2', 'E2.2', $lynxcurr$Expliquer les relations entre le millimètre, le centimètre, le mètre et le kilomètre, et utiliser des repères pour estimer des longueurs.$lynxcurr$, null, 43),
    ('4cbfe6d2-1248-5670-aee6-cc63fa5b96e8', '3', 'E', 'E2', 'E2.6', $lynxcurr$Lire l’heure en heures, en minutes et en secondes sur des horloges analogiques et numériques, et mesurer des durées à l’aide de minuteries.$lynxcurr$, null, 44),
    ('b4ea9031-4ba4-5b2f-8cc1-8a225bda2778', '3', 'F', 'F1', 'F1.1', $lynxcurr$Estimer et calculer la monnaie à rendre lors de transactions simples en argent comptant, avec des montants en dollars entiers ou de moins d’un dollar.$lynxcurr$, null, 46)
  ) as v (id, grade_code, strand_code, parent_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'mat' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  join public.curriculum_expectations p on p.subject_id = s.id and p.grade_code = g.code
    and p.curriculum_version = 'mat-2020' and p.code = v.parent_code and p.kind = 'overall'
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'mat-2020' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 34 then
    raise exception 'curriculum seed: %: % of % contenus (specific attentes) written (a missing subject, grade, strand or overall attente, or an attente the database has with another kind, strand or parent)',
      'mat-2020-3e.json', v_count, 34;
  end if;

  -- mat-2020-5e.json: 12 overall attentes
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, null::uuid,
    'overall'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'mat-2020', false, $lynxcurr$Résumé paraphrasé du curriculum de mathématiques de l’Ontario (2020), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('f09f146c-b1fd-5b5f-a97d-96fda0234741', '5', 'A', 'A1', $lynxcurr$Mettre en pratique des habiletés socioémotionnelles (reconnaître et gérer ses émotions, persévérer, collaborer, avoir confiance en soi, penser de façon critique et créative) en utilisant les processus mathématiques dans tous les domaines.$lynxcurr$, null, 1),
    ('248abcfc-c981-54a5-ab0e-8bd1816e487c', '5', 'B', 'B1', $lynxcurr$Démontrer une compréhension des nombres naturels, des fractions et des nombres décimaux jusqu’aux centièmes.$lynxcurr$, null, 2),
    ('4a645f2f-c96a-58b3-91bf-1ab698d42a28', '5', 'B', 'B2', $lynxcurr$Utiliser ses connaissances des nombres et des opérations pour résoudre des problèmes de la vie courante.$lynxcurr$, null, 10),
    ('0a22aaf7-8111-5db4-8205-ef02169346e9', '5', 'C', 'C1', $lynxcurr$Reconnaître, décrire, prolonger et créer diverses suites, dont des suites tirées de la vie courante, et faire des prédictions à leur sujet.$lynxcurr$, null, 17),
    ('96c9371e-cb74-5400-bfdc-baf1afa6f97a', '5', 'C', 'C2', $lynxcurr$Démontrer une compréhension des variables, des expressions, des égalités et des inégalités, et appliquer cette compréhension dans divers contextes.$lynxcurr$, null, 21),
    ('c103dba1-fc70-5f3e-b284-49366ad05dde', '5', 'C', 'C3', $lynxcurr$Résoudre des problèmes et créer des représentations informatiques de situations mathématiques à l’aide de concepts et d’habiletés de codage.$lynxcurr$, null, 24),
    ('fe9ef90f-cf72-5518-bec6-4986a50791f4', '5', 'C', 'C4', $lynxcurr$Appliquer le processus de modélisation mathématique pour représenter et analyser des situations de la vie courante, faire des prédictions et mieux les comprendre.$lynxcurr$, null, 27),
    ('5045e215-a9ab-50a4-b9a2-fd3fbd8a698e', '5', 'D', 'D1', $lynxcurr$Gérer, analyser et utiliser des données pour formuler des arguments convaincants et prendre des décisions éclairées dans des contextes de la vie courante.$lynxcurr$, null, 28),
    ('16337d19-fa81-5374-8e83-5f0af9eae883', '5', 'D', 'D2', $lynxcurr$Décrire la probabilité que des événements se produisent et utiliser cette information pour faire des prédictions.$lynxcurr$, null, 34),
    ('1cbfff00-7c73-5830-81e8-608784a3b54f', '5', 'E', 'E1', $lynxcurr$Décrire et représenter des formes, des positions et des déplacements en appliquant des propriétés géométriques et des relations spatiales pour s’orienter dans le monde qui nous entoure.$lynxcurr$, null, 37),
    ('d2ede362-d94a-550c-aae9-206e70e652c7', '5', 'E', 'E2', $lynxcurr$Comparer, estimer et déterminer des mesures dans divers contextes.$lynxcurr$, null, 40),
    ('278977be-bdd0-5e13-8fa8-1a6348d818ca', '5', 'F', 'F1', $lynxcurr$Démontrer une compréhension de la valeur de l’argent et de notions financières de base, et les appliquer à des situations de la vie courante.$lynxcurr$, null, 43)
  ) as v (id, grade_code, strand_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'mat' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'mat-2020' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 12 then
    raise exception 'curriculum seed: %: % of % overall attentes written (a missing subject, grade, strand, or an attente the database has with another kind, strand or parent)',
      'mat-2020-5e.json', v_count, 12;
  end if;
  -- mat-2020-5e.json: 33 contenus (specific attentes)
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, p.id,
    'specific'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'mat-2020', false, $lynxcurr$Résumé paraphrasé du curriculum de mathématiques de l’Ontario (2020), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('34510a4d-5aae-5785-a594-313862afdee4', '5', 'B', 'B1', 'B1.1', $lynxcurr$Lire, représenter, composer et décomposer des nombres naturels jusqu’à 100 000, et décrire comment on les utilise dans la vie courante.$lynxcurr$, null, 3),
    ('e5a12ca4-0275-51ae-9ece-3ab8a9b9f566', '5', 'B', 'B1', 'B1.2', $lynxcurr$Comparer et ordonner des nombres naturels jusqu’à 100 000 dans divers contextes.$lynxcurr$, null, 4),
    ('425096dc-6fcb-5ad0-9ab5-c643f556b785', '5', 'B', 'B1', 'B1.3', $lynxcurr$Représenter, comparer et ordonner, à l’aide de dessins et de modèles, les fractions obtenues dans différentes situations de partage équitable.$lynxcurr$, null, 5),
    ('edfa6dbd-4c6e-5283-a486-0c406eb52dfe', '5', 'B', 'B1', 'B1.5', $lynxcurr$Représenter des fractions équivalentes à l’aide de modèles et de droites numériques.$lynxcurr$, null, 6),
    ('8398d89a-62b7-5e6b-ba57-876f664f72b8', '5', 'B', 'B1', 'B1.6', $lynxcurr$Comparer et ordonner des fractions et des nombres décimaux jusqu’aux centièmes.$lynxcurr$, null, 7),
    ('59dd057b-64d9-5428-bc20-16aecf17e633', '5', 'B', 'B1', 'B1.7', $lynxcurr$Établir des liens entre les fractions et les nombres décimaux (dixièmes et centièmes).$lynxcurr$, null, 8),
    ('8e860ad7-d1b3-559d-ae45-0cc6c417b904', '5', 'B', 'B1', 'B1.8', $lynxcurr$Arrondir des nombres décimaux au dixième près dans divers contextes.$lynxcurr$, null, 9),
    ('81b94b7a-17d2-55d7-b4b5-522ce2b76fdb', '5', 'B', 'B2', 'B2.1', $lynxcurr$Utiliser les propriétés des opérations et les liens entre elles pour résoudre des problèmes à une ou plusieurs étapes avec des nombres naturels et des nombres décimaux, et vérifier ses calculs.$lynxcurr$, null, 11),
    ('6c9a16f3-5c75-5a09-a9f1-93c8afb9cda9', '5', 'B', 'B2', 'B2.2', $lynxcurr$Se rappeler les faits de multiplication de 0 × 0 à 12 × 12 et les faits de division qui s’y rattachent.$lynxcurr$, null, 12),
    ('205f3ad1-bc37-58fc-9550-85e6cffdf397', '5', 'B', 'B2', 'B2.4', $lynxcurr$Représenter et résoudre des problèmes d’addition et de soustraction de nombres naturels dont la somme ne dépasse pas 100 000 et de nombres décimaux jusqu’aux centièmes, à l’aide d’outils, de stratégies et d’algorithmes appropriés.$lynxcurr$, null, 13),
    ('f2f9930a-cae3-579e-866a-25528e5f5e33', '5', 'B', 'B2', 'B2.6', $lynxcurr$Représenter et résoudre des problèmes de multiplication de nombres naturels à deux chiffres par des nombres à deux chiffres, à l’aide du modèle d’aire et d’algorithmes.$lynxcurr$, null, 14),
    ('89d2c8ee-de9a-5660-9d8c-34d7e85fa1df', '5', 'B', 'B2', 'B2.7', $lynxcurr$Représenter et résoudre des problèmes de division de nombres naturels à trois chiffres par des nombres à deux chiffres, à l’aide du modèle d’aire et d’algorithmes, et interpréter le reste selon le contexte.$lynxcurr$, null, 15),
    ('76c2f5d9-7b33-5c95-8dd3-161ab9bda3a4', '5', 'B', 'B2', 'B2.8', $lynxcurr$Multiplier et diviser des nombres naturels à un chiffre par des fractions unitaires, à l’aide d’outils et de dessins.$lynxcurr$, null, 16),
    ('b5338861-e576-5ff4-a466-6440f71fedef', '5', 'C', 'C1', 'C1.1', $lynxcurr$Reconnaître et décrire des suites à motif répété, des suites croissantes et des suites décroissantes, dont des suites croissantes linéaires, y compris dans la vie courante.$lynxcurr$, null, 18),
    ('917571dd-14b3-571f-b6a7-8a653e9126f1', '5', 'C', 'C1', 'C1.2', $lynxcurr$Créer des suites croissantes et les traduire d’une représentation à une autre, dont des tables de valeurs et des graphiques.$lynxcurr$, null, 19),
    ('04b7c2a3-d812-5af0-a23a-b27e3efbb279', '5', 'C', 'C1', 'C1.3', $lynxcurr$Déterminer la règle d’une suite pour la prolonger, trouver des éléments manquants et justifier des prédictions.$lynxcurr$, null, 20),
    ('79b7dca4-845a-55de-8d55-069dad1580e6', '5', 'C', 'C2', 'C2.1', $lynxcurr$Traduire des relations d’égalité d’une représentation à une autre, par exemple de mots en expressions algébriques ou en représentations visuelles.$lynxcurr$, null, 22),
    ('3eaccfa0-42e1-5288-90bc-dc24aebf2c32', '5', 'C', 'C2', 'C2.3', $lynxcurr$Résoudre des équations comprenant des nombres naturels jusqu’à 100 dans divers contextes, et vérifier les solutions.$lynxcurr$, null, 23),
    ('58c0dda3-2b1c-5344-8710-ad9ba22aea41', '5', 'C', 'C3', 'C3.1', $lynxcurr$Écrire et exécuter du code comprenant des instructions conditionnelles et d’autres structures de contrôle pour résoudre des problèmes.$lynxcurr$, null, 25),
    ('cdc13e20-f8e6-5b30-b1f8-6ec6fdcdc3af', '5', 'C', 'C3', 'C3.2', $lynxcurr$Lire et modifier du code existant comprenant des instructions conditionnelles et d’autres structures de contrôle, et décrire l’effet des changements sur le résultat.$lynxcurr$, null, 26),
    ('f9614bb3-ca4f-531f-bfba-48d9c5ec96e7', '5', 'D', 'D1', 'D1.1', $lynxcurr$Distinguer les données discrètes et les données continues, et donner des exemples de chacune.$lynxcurr$, null, 29),
    ('44903209-4cb6-58c7-92e8-275d1475d16b', '5', 'D', 'D1', 'D1.2', $lynxcurr$Recueillir des données par des observations, des expériences, des entrevues ou des sources secondaires pour répondre à des questions d’intérêt, et les organiser dans des tableaux.$lynxcurr$, null, 30),
    ('36853d02-8879-556c-bfee-e0dca1334ffd', '5', 'D', 'D1', 'D1.3', $lynxcurr$Choisir le type de diagramme le mieux adapté à un ensemble de données, dont le diagramme à bandes empilées, le construire avec une source, un titre, des étiquettes et une échelle appropriée, et justifier son choix.$lynxcurr$, null, 31),
    ('fc45c73f-6238-520a-8769-5df728fd2315', '5', 'D', 'D1', 'D1.5', $lynxcurr$Déterminer la moyenne, la médiane et le mode d’ensembles de données comprenant des nombres naturels et des nombres décimaux, et expliquer ce que chaque mesure indique.$lynxcurr$, null, 32),
    ('533578fb-51ac-5384-8e46-aafeb4844f94', '5', 'D', 'D1', 'D1.6', $lynxcurr$Analyser des données présentées de diverses façons, dont des diagrammes trompeurs, en posant des questions et en y répondant, tirer des conclusions, puis formuler des arguments convaincants et prendre des décisions éclairées.$lynxcurr$, null, 33),
    ('896d50a6-edd3-5c18-80d7-aae01b0b8f6a', '5', 'D', 'D2', 'D2.1', $lynxcurr$Exprimer à l’aide de fractions la probabilité que des événements se produisent, la situer sur une ligne de probabilité et s’en servir pour faire des prédictions.$lynxcurr$, null, 35),
    ('cbb25d2e-23c7-5227-87c2-0e4fbf6a6c10', '5', 'D', 'D2', 'D2.2', $lynxcurr$Déterminer et comparer la probabilité théorique et la probabilité expérimentale d’un événement.$lynxcurr$, null, 36),
    ('f155392a-39ae-55b4-9b58-27c3838fc5c4', '5', 'E', 'E1', 'E1.1', $lynxcurr$Reconnaître les propriétés géométriques des triangles et construire différents types de triangles à partir de la mesure de leurs côtés ou de leurs angles.$lynxcurr$, null, 38),
    ('abadfdee-1358-5c63-8d73-89195d9eb950', '5', 'E', 'E1', 'E1.4', $lynxcurr$Situer et lire des points dans le premier quadrant d’un plan cartésien à l’aide de diverses échelles, et décrire les translations qui déplacent un point d’une position à une autre.$lynxcurr$, null, 39),
    ('507b2bdc-4f65-5d0d-be82-13b2b58a4b83', '5', 'E', 'E2', 'E2.4', $lynxcurr$Expliquer comment fonctionne un rapporteur d’angle, s’en servir pour mesurer et construire des angles jusqu’à 180°, et estimer la mesure d’angles à l’aide d’angles repères.$lynxcurr$, null, 41),
    ('270ca270-fb51-5d57-a94b-b82ba3587c51', '5', 'E', 'E2', 'E2.5', $lynxcurr$Utiliser les liens entre l’aire du rectangle, du parallélogramme et du triangle pour établir les formules d’aire du parallélogramme et du triangle, et résoudre des problèmes connexes.$lynxcurr$, null, 42),
    ('8a269420-d148-5dc6-9ee2-3face4f2a899', '5', 'F', 'F1', 'F1.2', $lynxcurr$Estimer et calculer le coût de transactions comprenant plusieurs articles en dollars et en cents, taxe de vente comprise, à l’aide de diverses stratégies.$lynxcurr$, null, 44),
    ('cc8dead0-3b13-59bd-a765-e0c578c8fbea', '5', 'F', 'F1', 'F1.3', $lynxcurr$Concevoir des budgets simples pour divers scénarios et expliquer en quoi un budget aide à prendre des décisions financières.$lynxcurr$, null, 45)
  ) as v (id, grade_code, strand_code, parent_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'mat' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  join public.curriculum_expectations p on p.subject_id = s.id and p.grade_code = g.code
    and p.curriculum_version = 'mat-2020' and p.code = v.parent_code and p.kind = 'overall'
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'mat-2020' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 33 then
    raise exception 'curriculum seed: %: % of % contenus (specific attentes) written (a missing subject, grade, strand or overall attente, or an attente the database has with another kind, strand or parent)',
      'mat-2020-5e.json', v_count, 33;
  end if;

  -- sci-2022-3e.json: 11 overall attentes
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, null::uuid,
    'overall'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'sci-2022', false, $lynxcurr$Résumé paraphrasé du curriculum de sciences et technologie de l’Ontario (2022), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('a5daca8d-1c73-5bdb-a5af-71e29be760eb', '3', 'A', 'A1', $lynxcurr$Utiliser un processus de recherche scientifique, un processus d’expérimentation scientifique et un processus de design en ingénierie pour mener des investigations, en respectant les consignes de santé et de sécurité.$lynxcurr$, null, 1),
    ('cb2e085d-0ffc-54fe-bd57-34441e4adad1', '3', 'A', 'A2', $lynxcurr$Utiliser le codage dans des investigations et pour modéliser des concepts, et évaluer l’incidence du codage et des technologies émergentes sur la vie quotidienne.$lynxcurr$, null, 7),
    ('ce78e90e-82fc-5e1e-9923-e90e7dfc28bc', '3', 'A', 'A3', $lynxcurr$Analyser des applications de la science et de la technologie dans divers contextes et reconnaître les contributions de personnes et de communautés diverses.$lynxcurr$, null, 10),
    ('67aa0fdd-16d8-5ec3-a333-11cf59a6534d', '3', 'B', 'B1', $lynxcurr$Évaluer l’importance des plantes pour les humains et l’environnement, ainsi que l’incidence des activités humaines sur les plantes.$lynxcurr$, null, 14),
    ('3cb18270-9544-580b-ac68-5402498c9fda', '3', 'B', 'B2', $lynxcurr$Démontrer une compréhension de la croissance et des changements chez les plantes, de leurs caractéristiques et de leurs besoins.$lynxcurr$, null, 17),
    ('218956eb-35f3-55c1-92b0-35cd906b1073', '3', 'C', 'C1', $lynxcurr$Évaluer l’incidence de diverses forces sur la société et l’environnement.$lynxcurr$, null, 23),
    ('406ecff6-5a1b-52ce-b17f-11bf4b030a9d', '3', 'C', 'C2', $lynxcurr$Démontrer une compréhension des forces qui causent le mouvement, dont les forces de contact et les forces à distance.$lynxcurr$, null, 26),
    ('a1c61afc-abb7-51e5-8b6f-60be1e8007bf', '3', 'D', 'D1', $lynxcurr$Évaluer l’importance des structures solides et stables pour la société et l’environnement.$lynxcurr$, null, 30),
    ('8feee3e3-8eb3-5888-8268-af259de4392b', '3', 'D', 'D2', $lynxcurr$Démontrer une compréhension de la solidité et de la stabilité des structures naturelles et fabriquées.$lynxcurr$, null, 33),
    ('6a40e476-1c07-5dea-aa3c-f69131aafc50', '3', 'E', 'E1', $lynxcurr$Évaluer l’importance des sols pour la société et l’environnement, ainsi que l’incidence des activités humaines sur les sols.$lynxcurr$, null, 37),
    ('510c2a3f-60af-50dd-b36d-ef3269b01103', '3', 'E', 'E2', $lynxcurr$Démontrer une compréhension de la composition et des types de sols, et des liens entre les sols et les êtres vivants.$lynxcurr$, null, 40)
  ) as v (id, grade_code, strand_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'sci' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'sci-2022' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 11 then
    raise exception 'curriculum seed: %: % of % overall attentes written (a missing subject, grade, strand, or an attente the database has with another kind, strand or parent)',
      'sci-2022-3e.json', v_count, 11;
  end if;
  -- sci-2022-3e.json: 32 contenus (specific attentes)
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, p.id,
    'specific'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'sci-2022', false, $lynxcurr$Résumé paraphrasé du curriculum de sciences et technologie de l’Ontario (2022), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('73f2cb30-160b-52bc-8403-716d0fde9cb6', '3', 'A', 'A1', 'A1.1', $lynxcurr$Utiliser un processus de recherche scientifique pour explorer des questions liées aux concepts à l’étude.$lynxcurr$, null, 2),
    ('918f3747-1b8d-518b-a66c-07a4a80a2088', '3', 'A', 'A1', 'A1.2', $lynxcurr$Utiliser un processus d’expérimentation scientifique pour faire des prédictions, les vérifier et observer des phénomènes liés aux concepts à l’étude.$lynxcurr$, null, 3),
    ('0f23a24d-99bb-5dc6-aff4-0ac1a4d847dd', '3', 'A', 'A1', 'A1.3', $lynxcurr$Utiliser un processus de design en ingénierie pour concevoir, construire, mettre à l’essai et améliorer une solution à un problème concret.$lynxcurr$, null, 4),
    ('6e56fc5b-e5ba-5239-8743-4225de6128d0', '3', 'A', 'A1', 'A1.4', $lynxcurr$Suivre les consignes de santé et de sécurité pendant les investigations, dont le port de l’équipement de protection et l’utilisation sécuritaire des outils et du matériel.$lynxcurr$, null, 5),
    ('c6c22c8e-5de4-5dc3-bae0-2d36b1c0b7ee', '3', 'A', 'A1', 'A1.5', $lynxcurr$Communiquer ses résultats en utilisant le vocabulaire scientifique et technologique et des formes adaptées à l’intention et au public.$lynxcurr$, null, 6),
    ('55a0a1a4-2da8-5fb0-b4d6-c4c18d03059c', '3', 'A', 'A2', 'A2.1', $lynxcurr$Écrire et exécuter du code pour mener des investigations et modéliser des concepts, par exemple à l’aide d’instructions en séquence et de boucles.$lynxcurr$, null, 8),
    ('8749322c-5df9-5e94-a433-0a503b33bffd', '3', 'A', 'A2', 'A2.2', $lynxcurr$Reconnaître et décrire l’incidence du codage et des technologies émergentes sur la vie quotidienne, y compris dans les métiers spécialisés.$lynxcurr$, null, 9),
    ('e9c316be-deff-5fd9-b388-338f8e58f930', '3', 'A', 'A3', 'A3.1', $lynxcurr$Décrire des applications pratiques des concepts scientifiques et technologiques à l’étude, dont des métiers qui s’y rattachent.$lynxcurr$, null, 11),
    ('f6beed48-3687-5336-aa6d-dc8b21d2e8d3', '3', 'A', 'A3', 'A3.2', $lynxcurr$Explorer comment la science et la technologie peuvent être combinées à d’autres matières pour répondre à des problèmes concrets.$lynxcurr$, null, 12),
    ('9e98f181-9192-5782-a357-3e32865f02f6', '3', 'A', 'A3', 'A3.3', $lynxcurr$Reconnaître les contributions à la science et à la technologie de personnes de diverses communautés, dont les Premières Nations, les Métis, les Inuit et les communautés francophones.$lynxcurr$, null, 13),
    ('b14c3029-c52f-51b7-9fb9-c3c093a56e40', '3', 'B', 'B1', 'B1.1', $lynxcurr$Évaluer l’importance des plantes pour les humains et les autres êtres vivants, en tenant compte de divers points de vue, et proposer des façons de protéger les plantes indigènes et leurs habitats.$lynxcurr$, null, 15),
    ('1d006a96-071b-5798-a706-eeaf2a2d530c', '3', 'B', 'B1', 'B1.2', $lynxcurr$Évaluer l’incidence de diverses activités humaines sur les plantes et proposer des moyens d’en réduire les effets nuisibles.$lynxcurr$, null, 16),
    ('e7d6249b-f6e1-5dff-a8bd-d9d089dff60a', '3', 'B', 'B2', 'B2.1', $lynxcurr$Décrire les besoins essentiels des plantes (air, eau, lumière, chaleur, espace, nutriments).$lynxcurr$, null, 18),
    ('d763b651-b685-55c2-8890-5d39446ab9e1', '3', 'B', 'B2', 'B2.2', $lynxcurr$Nommer les principales parties d’une plante (racine, tige, feuille, fleur, graine, fruit) et décrire le rôle de chacune dans sa survie.$lynxcurr$, null, 19),
    ('89822a91-5d6d-573c-ab70-dca2301c8a14', '3', 'B', 'B2', 'B2.3', $lynxcurr$Décrire les changements que subissent différentes plantes au cours de leur cycle de vie.$lynxcurr$, null, 20),
    ('6ae78da6-c7ad-5179-bd9b-28531b17a21a', '3', 'B', 'B2', 'B2.4', $lynxcurr$Expliquer que la plupart des plantes tirent leur énergie directement du Soleil et qu’elles fournissent de l’énergie aux autres êtres vivants.$lynxcurr$, null, 21),
    ('a6832993-190d-5d4c-8040-927cd3073197', '3', 'B', 'B2', 'B2.5', $lynxcurr$Décrire des façons dont les plantes et les animaux dépendent les uns des autres, par exemple la pollinisation, la dispersion des graines, la nourriture et l’abri.$lynxcurr$, null, 22),
    ('1f24175b-3f14-52ca-8e39-0c35d21dda4c', '3', 'C', 'C1', 'C1.1', $lynxcurr$Évaluer les effets de forces naturelles, comme le vent et l’eau en mouvement, sur l’environnement naturel et bâti, et proposer des façons d’en réduire les effets nuisibles.$lynxcurr$, null, 24),
    ('8895d586-7441-5905-a464-50b33ffd6aa4', '3', 'C', 'C1', 'C1.2', $lynxcurr$Évaluer l’utilité d’outils et de dispositifs qui utilisent des forces dans la vie quotidienne, en tenant compte de leurs effets sur les personnes et l’environnement.$lynxcurr$, null, 25),
    ('3c590299-4c91-5cc5-b37d-e62d319fe69b', '3', 'C', 'C2', 'C2.1', $lynxcurr$Définir une force comme une poussée ou une traction qui peut mettre un objet en mouvement, l’arrêter ou changer sa direction.$lynxcurr$, null, 27),
    ('b95f5e26-8b71-5730-b3c7-7edc074f34fd', '3', 'C', 'C2', 'C2.2', $lynxcurr$Distinguer les forces de contact, comme le frottement, et les forces à distance, comme la gravité, le magnétisme et l’électricité statique.$lynxcurr$, null, 28),
    ('8f658af4-eb93-5715-a780-c73ad0b956cf', '3', 'C', 'C2', 'C2.3', $lynxcurr$Décrire comment une force peut changer la forme, la vitesse ou la direction d’un objet.$lynxcurr$, null, 29),
    ('352ce230-d715-5a5c-83ce-2d44b0f0aa05', '3', 'D', 'D1', 'D1.1', $lynxcurr$Évaluer l’incidence de diverses structures sur la société et l’environnement, et proposer des façons d’en réduire les effets nuisibles.$lynxcurr$, null, 31),
    ('039f7b2c-7b44-52dd-84d4-edc6f557592c', '3', 'D', 'D1', 'D1.2', $lynxcurr$Évaluer l’importance de construire des structures sécuritaires et durables qui répondent aux besoins des personnes qui les utilisent.$lynxcurr$, null, 32),
    ('ccd2f31a-e3f8-5a95-a169-8d3ce24961b7', '3', 'D', 'D2', 'D2.1', $lynxcurr$Décrire une structure comme un objet d’une forme et d’une taille précises qui sert à supporter ou à contenir quelque chose.$lynxcurr$, null, 34),
    ('4dbed9f8-2776-5308-ae5c-5d89f8fb79d4', '3', 'D', 'D2', 'D2.2', $lynxcurr$Décrire comment les matériaux, la forme et la base d’une structure influent sur sa solidité et sa stabilité.$lynxcurr$, null, 35),
    ('4aa135f8-80c2-583f-b6a5-128b03bfb89e', '3', 'D', 'D2', 'D2.3', $lynxcurr$Reconnaître des structures naturelles et fabriquées, et comparer la façon dont elles restent solides et stables.$lynxcurr$, null, 36),
    ('dc404bac-2d47-585c-9cb4-25835a80fe27', '3', 'E', 'E1', 'E1.1', $lynxcurr$Évaluer l’importance des sols pour les êtres vivants et pour des activités humaines comme l’agriculture et la construction, et proposer des façons de les protéger.$lynxcurr$, null, 38),
    ('3345d34c-2599-5966-9245-23fdaa3d7296', '3', 'E', 'E1', 'E1.2', $lynxcurr$Évaluer l’incidence d’activités humaines sur les sols, comme l’érosion et la pollution, et proposer des moyens d’en réduire les effets nuisibles.$lynxcurr$, null, 39),
    ('92f7e487-dbaa-5bee-a0da-128d5b903283', '3', 'E', 'E2', 'E2.1', $lynxcurr$Décrire la composition des sols (particules minérales, humus, air, eau, êtres vivants).$lynxcurr$, null, 41),
    ('5c370cf5-5c75-5f9a-ac40-16a1483ebcc4', '3', 'E', 'E2', 'E2.2', $lynxcurr$Comparer différents types de sols, comme les sols sableux, argileux et limoneux, selon leurs caractéristiques, dont leur capacité à retenir l’eau.$lynxcurr$, null, 42),
    ('4e8c23aa-9856-5a95-b3f5-8e6c6cb8db6c', '3', 'E', 'E2', 'E2.3', $lynxcurr$Décrire le rôle des êtres vivants du sol, comme les vers de terre, dans la décomposition des matières organiques et le compostage.$lynxcurr$, null, 43)
  ) as v (id, grade_code, strand_code, parent_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'sci' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  join public.curriculum_expectations p on p.subject_id = s.id and p.grade_code = g.code
    and p.curriculum_version = 'sci-2022' and p.code = v.parent_code and p.kind = 'overall'
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'sci-2022' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 32 then
    raise exception 'curriculum seed: %: % of % contenus (specific attentes) written (a missing subject, grade, strand or overall attente, or an attente the database has with another kind, strand or parent)',
      'sci-2022-3e.json', v_count, 32;
  end if;

  -- sci-2022-5e.json: 11 overall attentes
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, null::uuid,
    'overall'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'sci-2022', false, $lynxcurr$Résumé paraphrasé du curriculum de sciences et technologie de l’Ontario (2022), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('f3fb3cb9-2672-5320-b2d5-3b25dfc8dd94', '5', 'A', 'A1', $lynxcurr$Utiliser un processus de recherche scientifique, un processus d’expérimentation scientifique et un processus de design en ingénierie pour mener des investigations, en respectant les consignes de santé et de sécurité.$lynxcurr$, null, 1),
    ('eeda3fd3-2ca9-59b4-be20-dfd579cfe889', '5', 'A', 'A2', $lynxcurr$Utiliser le codage dans des investigations et pour modéliser des concepts, et évaluer l’incidence du codage et des technologies émergentes sur la vie quotidienne.$lynxcurr$, null, 7),
    ('6ff142fe-c2f9-58ef-8692-b49163deafa8', '5', 'A', 'A3', $lynxcurr$Analyser des applications de la science et de la technologie dans divers contextes et reconnaître les contributions de personnes et de communautés diverses.$lynxcurr$, null, 10),
    ('7f25b8ab-1aec-53e7-a6fe-c28cde95274c', '5', 'B', 'B1', $lynxcurr$Évaluer l’incidence de facteurs sociaux et environnementaux et de diverses technologies sur la santé humaine.$lynxcurr$, null, 14),
    ('ad418c21-f384-5581-8528-e2113dc0e679', '5', 'B', 'B2', $lynxcurr$Démontrer une compréhension de la structure et de la fonction des systèmes du corps humain et des interactions entre ces systèmes.$lynxcurr$, null, 17),
    ('8db4c19c-cb3a-57ea-a14d-005aeaf6a138', '5', 'C', 'C1', $lynxcurr$Évaluer l’incidence sur la société et l’environnement des matériaux que les humains utilisent et des changements qu’ils leur font subir.$lynxcurr$, null, 21),
    ('2213a197-a6f4-5a7f-8763-76b88c03d8fa', '5', 'C', 'C2', $lynxcurr$Démontrer une compréhension des propriétés de la matière, des changements d’état et des changements physiques et chimiques.$lynxcurr$, null, 24),
    ('058ead05-4688-5431-bbcb-cde14eb38b0a', '5', 'D', 'D1', $lynxcurr$Évaluer l’incidence des forces sur les structures, ainsi que l’incidence des structures sur la société et l’environnement.$lynxcurr$, null, 29),
    ('31175121-aaac-5b52-8109-07d2d1b129e4', '5', 'D', 'D2', $lynxcurr$Démontrer une compréhension des forces qui agissent sur les structures et de leurs effets.$lynxcurr$, null, 32),
    ('2a2e97aa-276c-5c50-a00d-d96849d154c3', '5', 'E', 'E1', $lynxcurr$Évaluer l’incidence de l’utilisation de l’énergie et des ressources sur la société et l’environnement, et proposer des moyens de les conserver.$lynxcurr$, null, 36),
    ('a0400438-a99b-5b1c-a7ab-2389d40c501e', '5', 'E', 'E2', $lynxcurr$Démontrer une compréhension des formes d’énergie, des transformations de l’énergie et de la conservation de l’énergie et des ressources.$lynxcurr$, null, 39)
  ) as v (id, grade_code, strand_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'sci' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'sci-2022' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 11 then
    raise exception 'curriculum seed: %: % of % overall attentes written (a missing subject, grade, strand, or an attente the database has with another kind, strand or parent)',
      'sci-2022-5e.json', v_count, 11;
  end if;
  -- sci-2022-5e.json: 32 contenus (specific attentes)
  insert into public.curriculum_expectations (id, subject_id, grade_code, strand_id, parent_id,
    kind, code, text_fr, text_en, curriculum_version, is_verified, source_note, sort_order)
  select v.id::uuid, s.id, g.code, st.id, p.id,
    'specific'::public.expectation_kind, v.code, v.text_fr,
    v.text_en, 'sci-2022', false, $lynxcurr$Résumé paraphrasé du curriculum de sciences et technologie de l’Ontario (2022), à vérifier contre le document officiel.$lynxcurr$, v.sort_order
  from (values
    ('d04f9cc9-01f7-52cd-b3ef-311f16e73f4c', '5', 'A', 'A1', 'A1.1', $lynxcurr$Utiliser un processus de recherche scientifique pour explorer des questions liées aux concepts à l’étude.$lynxcurr$, null, 2),
    ('01268c4f-5eda-5142-b318-fd710d439530', '5', 'A', 'A1', 'A1.2', $lynxcurr$Utiliser un processus d’expérimentation scientifique pour faire des prédictions, les vérifier et observer des phénomènes liés aux concepts à l’étude.$lynxcurr$, null, 3),
    ('eccafd4d-b62f-5aad-b471-7a456cc0f172', '5', 'A', 'A1', 'A1.3', $lynxcurr$Utiliser un processus de design en ingénierie pour concevoir, construire, mettre à l’essai et améliorer une solution à un problème concret.$lynxcurr$, null, 4),
    ('dfb8d4a4-31ac-571e-81e6-8d93fc4d4980', '5', 'A', 'A1', 'A1.4', $lynxcurr$Suivre les consignes de santé et de sécurité pendant les investigations, dont le port de l’équipement de protection et l’utilisation sécuritaire des outils et du matériel.$lynxcurr$, null, 5),
    ('2d54d57e-ebb6-5fb8-8e0b-3021f1d914df', '5', 'A', 'A1', 'A1.5', $lynxcurr$Communiquer ses résultats en utilisant le vocabulaire scientifique et technologique et des formes adaptées à l’intention et au public.$lynxcurr$, null, 6),
    ('408c9e83-8a78-51f8-ba80-02eb3071e584', '5', 'A', 'A2', 'A2.1', $lynxcurr$Écrire et exécuter du code pour mener des investigations et modéliser des concepts, par exemple à l’aide d’instructions conditionnelles.$lynxcurr$, null, 8),
    ('a78141ba-3984-575e-8c67-93ee189ed0bd', '5', 'A', 'A2', 'A2.2', $lynxcurr$Reconnaître et décrire l’incidence du codage et des technologies émergentes sur la vie quotidienne, y compris dans les métiers spécialisés.$lynxcurr$, null, 9),
    ('adfad657-6fb8-53e1-b05d-3327a2ba2a64', '5', 'A', 'A3', 'A3.1', $lynxcurr$Décrire des applications pratiques des concepts scientifiques et technologiques à l’étude, dont des métiers qui s’y rattachent.$lynxcurr$, null, 11),
    ('b1794189-8d3e-579c-8e4d-e5ab8efe5f01', '5', 'A', 'A3', 'A3.2', $lynxcurr$Explorer comment la science et la technologie peuvent être combinées à d’autres matières pour répondre à des problèmes concrets.$lynxcurr$, null, 12),
    ('f5116fd1-909c-5932-a736-dad75d0fe9dd', '5', 'A', 'A3', 'A3.3', $lynxcurr$Reconnaître les contributions à la science et à la technologie de personnes de diverses communautés, dont les Premières Nations, les Métis, les Inuit et les communautés francophones.$lynxcurr$, null, 13),
    ('a6e03d20-7b83-580e-a80a-1b8582ef362f', '5', 'B', 'B1', 'B1.1', $lynxcurr$Évaluer les effets de divers facteurs sociaux et environnementaux sur la santé humaine et décrire des façons de réduire les effets nuisibles et de profiter des effets bénéfiques.$lynxcurr$, null, 15),
    ('0a7f0c92-de2e-59a7-9fa7-81d9443e5f26', '5', 'B', 'B1', 'B1.2', $lynxcurr$Évaluer l’incidence de diverses technologies sur la santé humaine, par exemple des outils de diagnostic ou des prothèses.$lynxcurr$, null, 16),
    ('776c0928-32a3-58c8-a119-5a412dd81e54', '5', 'B', 'B2', 'B2.1', $lynxcurr$Décrire la structure et la fonction des principaux organes de divers systèmes du corps humain (respiratoire, circulatoire, digestif, musculosquelettique, nerveux).$lynxcurr$, null, 18),
    ('52ed20f6-40ab-5e9b-8f6f-c1674a860e99', '5', 'B', 'B2', 'B2.2', $lynxcurr$Décrire comment les systèmes du corps humain interagissent pour assurer les fonctions vitales, par exemple les systèmes respiratoire et circulatoire.$lynxcurr$, null, 19),
    ('17da5f96-a4bd-5de7-96b0-83b24f524325', '5', 'B', 'B2', 'B2.3', $lynxcurr$Reconnaître des maladies et des troubles courants qui touchent les systèmes du corps humain, leurs causes possibles et des façons de les prévenir ou de les traiter.$lynxcurr$, null, 20),
    ('4fc13243-fa62-5b27-8b02-13d1636b6b72', '5', 'C', 'C1', 'C1.1', $lynxcurr$Évaluer les effets sur l’environnement de l’utilisation et de l’élimination de divers matériaux, et proposer des façons d’en limiter les effets, par exemple réduire, réutiliser et recycler.$lynxcurr$, null, 22),
    ('c68daa1d-0339-53b9-a8c1-ae47fc2ff3a5', '5', 'C', 'C1', 'C1.2', $lynxcurr$Évaluer l’utilité pour la société de procédés qui transforment la matière, comme la cuisson, le recyclage et le compostage, en tenant compte de leurs effets sur l’environnement.$lynxcurr$, null, 23),
    ('492553fe-b8c3-56e0-a3dd-2a8ba73c6c8b', '5', 'C', 'C2', 'C2.1', $lynxcurr$Décrire les propriétés des solides, des liquides et des gaz, dont la masse, le volume et la forme.$lynxcurr$, null, 25),
    ('bb9a8de1-92a2-58dc-ae43-a012aff5b820', '5', 'C', 'C2', 'C2.2', $lynxcurr$Expliquer les changements d’état (fusion, solidification, évaporation, condensation, sublimation) causés par un gain ou une perte de chaleur.$lynxcurr$, null, 26),
    ('6896ac5c-5abc-5815-b1c9-0841491c7267', '5', 'C', 'C2', 'C2.3', $lynxcurr$Distinguer les changements physiques, qui sont souvent réversibles, et les changements chimiques, qui produisent de nouvelles substances.$lynxcurr$, null, 27),
    ('ffed7169-0cef-5b7e-9e4a-db5c4815aad1', '5', 'C', 'C2', 'C2.4', $lynxcurr$Reconnaître les indices d’un changement chimique, comme la production d’un gaz, un changement de couleur, la formation d’un solide ou un dégagement de chaleur ou de lumière.$lynxcurr$, null, 28),
    ('36b6c735-1aa6-5cfe-afbf-18049b127e9a', '5', 'D', 'D1', 'D1.1', $lynxcurr$Évaluer les effets de phénomènes naturels, comme le vent, les séismes et les fortes chutes de neige, sur les structures, et décrire comment on conçoit des structures qui y résistent.$lynxcurr$, null, 30),
    ('ae1ede4f-a62b-5e69-a0b3-1062e480c515', '5', 'D', 'D1', 'D1.2', $lynxcurr$Évaluer l’incidence de structures sur la société et l’environnement en tenant compte de divers facteurs (coût, sécurité, matériaux, besoins de la communauté).$lynxcurr$, null, 31),
    ('47a9f308-2ec0-533b-a3ad-0a3825f81bc2', '5', 'D', 'D2', 'D2.1', $lynxcurr$Distinguer les forces internes (compression, tension, torsion, cisaillement) et externes.$lynxcurr$, null, 33),
    ('d85f56f1-6e1d-55ff-b806-2e31cdde587e', '5', 'D', 'D2', 'D2.2', $lynxcurr$Expliquer comment la forme et les matériaux d’une structure l’aident à résister aux forces.$lynxcurr$, null, 34),
    ('544affae-77ef-55df-bd87-475e7a22a956', '5', 'D', 'D2', 'D2.3', $lynxcurr$Décrire comment la grandeur et la direction d’une force, ainsi que l’endroit où elle s’applique, influent sur une structure.$lynxcurr$, null, 35),
    ('7bbc6091-1dd4-5467-8ce7-15804efd3c41', '5', 'E', 'E1', 'E1.1', $lynxcurr$Analyser les effets à long terme de l’utilisation de l’énergie et des ressources naturelles par les humains, et proposer des moyens de réduire ces effets.$lynxcurr$, null, 37),
    ('c33456eb-599a-5900-b8ac-d7d090d507b2', '5', 'E', 'E1', 'E1.2', $lynxcurr$Évaluer des technologies et des habitudes qui permettent d’économiser l’énergie et les ressources à la maison, à l’école et dans la communauté.$lynxcurr$, null, 38),
    ('dd55011a-2157-5a3c-a946-2c7a7885334e', '5', 'E', 'E2', 'E2.1', $lynxcurr$Reconnaître diverses formes d’énergie (mécanique, électrique, thermique, chimique, sonore, lumineuse) et décrire comment on les utilise au quotidien.$lynxcurr$, null, 40),
    ('7ddef767-605b-578b-9972-f1d32d6d17c2', '5', 'E', 'E2', 'E2.2', $lynxcurr$Décrire comment l’énergie se transforme d’une forme à une autre dans des appareils et des phénomènes courants.$lynxcurr$, null, 41),
    ('699079ca-2956-5543-92fb-94f5afbf0956', '5', 'E', 'E2', 'E2.3', $lynxcurr$Expliquer que l’énergie ne se crée pas et ne disparaît pas, mais qu’elle se transforme, souvent en partie en chaleur.$lynxcurr$, null, 42),
    ('86e918b5-45b0-52cc-998e-42378e71a10f', '5', 'E', 'E2', 'E2.4', $lynxcurr$Distinguer les sources d’énergie renouvelables et non renouvelables, et comparer leurs avantages et leurs inconvénients.$lynxcurr$, null, 43)
  ) as v (id, grade_code, strand_code, parent_code, code, text_fr, text_en, sort_order)
  join public.subjects s on s.code = 'sci' and s.board_id is null
  join public.grades g on g.code = v.grade_code and g.ordinal between s.grade_min and s.grade_max
  join public.curriculum_expectations p on p.subject_id = s.id and p.grade_code = g.code
    and p.curriculum_version = 'sci-2022' and p.code = v.parent_code and p.kind = 'overall'
  left join public.strands st on st.subject_id = s.id
    and st.curriculum_version = 'sci-2022' and st.code = v.strand_code
  where v.strand_code is null or st.id is not null
  on conflict (subject_id, grade_code, curriculum_version, code) do update
    set sort_order = excluded.sort_order
    where curriculum_expectations.kind = excluded.kind
      and curriculum_expectations.strand_id is not distinct from excluded.strand_id
      and curriculum_expectations.parent_id is not distinct from excluded.parent_id;
  get diagnostics v_count = row_count;
  if v_count <> 32 then
    raise exception 'curriculum seed: %: % of % contenus (specific attentes) written (a missing subject, grade, strand or overall attente, or an attente the database has with another kind, strand or parent)',
      'sci-2022-5e.json', v_count, 32;
  end if;

end $lynxseed$;
