import { readdirSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  CURRICULUM_QUOTE,
  curriculumExpectationId,
  curriculumStrandId,
  curriculumToSql,
  type CurriculumSource,
} from './curriculum-sql';
import { LYNX_CONTENT_NAMESPACE, uuidv5 } from './uuid';

const file = (grade: string) => ({
  official: false,
  verified: false,
  subjectCode: 'fra',
  curriculumVersion: 'fra-2023',
  sourceNote: 'Résumé paraphrasé, à vérifier.',
  strands: [
    { code: 'C', labelFr: 'Compréhension', labelEn: null },
    { code: 'D', labelFr: 'Composition', labelEn: null },
  ],
  expectations: [
    {
      grade,
      code: 'C1',
      kind: 'overall',
      strandCode: 'C',
      parentCode: null,
      textFr: 'Comprendre des textes.',
    },
    {
      grade,
      code: 'C1.1',
      kind: 'specific',
      strandCode: 'C',
      parentCode: 'C1',
      textFr: 'Faire des prédictions avant la lecture.',
    },
    {
      grade,
      code: 'C1.2',
      kind: 'specific',
      strandCode: 'C',
      parentCode: 'C1',
      textFr: 'Dégager l’idée principale d’un texte qu’elle ou il lit.',
    },
    {
      grade,
      code: 'D1',
      kind: 'overall',
      strandCode: 'D',
      parentCode: null,
      textFr: 'Planifier et rédiger de courts textes.',
    },
  ],
});

const sources = (): CurriculumSource[] => [
  { name: 'fra-2023-5e.json', json: file('5') },
  { name: 'fra-2023-3e.json', json: JSON.stringify(file('3')) },
];

describe('curriculumToSql', () => {
  it('is deterministic, whatever the order of the files', () => {
    const sql = curriculumToSql(sources());
    expect(curriculumToSql([...sources()].reverse())).toBe(sql);
    expect(sql).toMatch(/^-- Generated by `pnpm library:seed` from content\/curriculum\./);
    expect(sql).toContain(
      '-- Curriculum sample: 2 files, 2 strands, 8 attentes (4 overall, 4 contenus).',
    );
    expect(sql).toMatch(/do \$lynxseed\$\n[\s\S]*\nend \$lynxseed\$;\n$/);
    // The 3e file comes first, and the strands are written once for both grades.
    expect(sql.indexOf('fra-2023-3e.json: 2 overall')).toBeLessThan(
      sql.indexOf('fra-2023-5e.json: 2 overall'),
    );
    expect(sql.match(/insert into public\.strands/g)).toHaveLength(1);
  });

  it('writes UUIDv5 ids, every row unverified, and each grade in file order', () => {
    const sql = curriculumToSql(sources());
    const id = curriculumExpectationId('fra', 'fra-2023', '3', 'C1.2');
    expect(id).toBe(uuidv5('curriculum/fra/fra-2023/3/C1.2', LYNX_CONTENT_NAMESPACE));
    expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    expect(curriculumExpectationId('fra', 'fra-2023', '5', 'C1.2')).not.toBe(id);
    expect(sql).toContain(
      `('${id}', '3', 'C', 'C1', 'C1.2', ${CURRICULUM_QUOTE}Dégager l’idée principale d’un texte qu’elle ou il lit.${CURRICULUM_QUOTE}, null, 3)`,
    );
    // D1 comes fourth in its grade although it is the second overall attente.
    expect(sql).toContain(
      `('${curriculumExpectationId('fra', 'fra-2023', '3', 'D1')}', '3', 'D', 'D1', ${CURRICULUM_QUOTE}Planifier et rédiger de courts textes.${CURRICULUM_QUOTE}, null, 4)`,
    );
    expect(sql).toContain(
      `('${curriculumStrandId('fra', 'fra-2023', 'D')}', 'D', ${CURRICULUM_QUOTE}Composition${CURRICULUM_QUOTE}, null, 2)`,
    );
    // is_verified is false in every statement, with the file's source note.
    expect(sql.match(/v\.text_en, 'fra-2023', false, \$lynxcurr\$Résumé paraphrasé/g)).toHaveLength(
      4,
    );
  });

  it('keeps the rows the database already has: only their sort order follows the file', () => {
    const sql = curriculumToSql(sources());
    const updates = sql.match(/do update\n\s+set [^;]*;/g)!;
    expect(updates).toHaveLength(5); // strands once, then overall and contenus for each file
    for (const update of updates) {
      expect(update).toMatch(/^do update\n\s+set sort_order = excluded\.sort_order[;\n]/);
      expect(update).not.toMatch(/text_fr|label_fr|is_verified|source_note|\bid =/);
    }
    // An existing attente of another kind, strand or parent is not touched, so the count
    // check raises.
    expect(updates[1]).toContain('where curriculum_expectations.kind = excluded.kind');
    expect(updates[1]).toContain('strand_id is not distinct from excluded.strand_id');
    expect(updates[1]).toContain('parent_id is not distinct from excluded.parent_id');
    expect(sql).toContain('  if v_count <> 2 then');
    expect(sql).toContain("and p.code = v.parent_code and p.kind = 'overall'");
    expect(sql).toContain('g.ordinal between s.grade_min and s.grade_max');
  });

  it('refuses official or verified text (D-030), and invalid files', () => {
    const official = { ...file('3'), official: true };
    expect(() => curriculumToSql([{ name: 'a.json', json: official }])).toThrow(
      'a.json: official: licenceConfirmationRequired',
    );
    const verified = { ...file('3'), verified: true };
    expect(() => curriculumToSql([{ name: 'a.json', json: verified }])).toThrow(
      'licenceConfirmationRequired',
    );
    expect(() => curriculumToSql([{ name: 'a.json', json: '{' }])).toThrow(
      'a.json: (file): invalidJson',
    );
    expect(() => curriculumToSql([])).toThrow('no curriculum file');
  });

  it('refuses files that disagree or overlap, and a contenu outside its attente’s strand', () => {
    const otherStrands = file('5');
    otherStrands.strands[1]!.labelFr = 'Écriture';
    expect(() =>
      curriculumToSql([
        { name: 'a.json', json: file('3') },
        { name: 'b.json', json: otherStrands },
      ]),
    ).toThrow('b.json: other strands than a.json for fra fra-2023');

    const sameGrade = file('3');
    sameGrade.expectations = [{ ...sameGrade.expectations[3]!, code: 'D2' }];
    expect(() =>
      curriculumToSql([
        { name: 'a.json', json: file('3') },
        { name: 'b.json', json: sameGrade },
      ]),
    ).toThrow('b.json: a.json already has fra fra-2023 3');

    const moved = file('3');
    moved.expectations[2]!.strandCode = 'D';
    expect(() => curriculumToSql([{ name: 'a.json', json: moved }])).toThrow(
      'a.json: 3 C1.2 is not in the strand of C1',
    );

    const tagged = file('3');
    tagged.expectations[0]!.textFr = `Comprendre ${CURRICULUM_QUOTE} des textes.`;
    expect(() => curriculumToSql([{ name: 'a.json', json: tagged }])).toThrow(
      'a.json: contains the quote tag $lynxcurr$',
    );
    tagged.expectations[0]!.textFr = 'Comprendre $lynxseed$ des textes.';
    expect(() => curriculumToSql([{ name: 'a.json', json: tagged }])).toThrow('$lynxseed$');
  });

  it('converts the curriculum sample of content/curriculum', () => {
    const dir = new URL('../../../content/curriculum/', import.meta.url);
    const files = readdirSync(dir).filter((f) => f.endsWith('.json'));
    const sql = curriculumToSql(
      files.map((name) => ({ name, json: readFileSync(new URL(name, dir), 'utf8') })),
    );
    expect(sql).toContain(`-- Curriculum sample: ${files.length} files,`);
    // The seed's own attentes are matched by code; their ids are never written again.
    expect(sql).not.toContain('20000000-0000-4000-8000-');
  });
});
